//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Client_Cars = new HashSet<Client_Cars>();
            this.Description = new HashSet<Description>();
            this.Order = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public string Mark { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
        public string LastTO { get; set; }
    
        public virtual ICollection<Client_Cars> Client_Cars { get; set; }
        public virtual ICollection<Description> Description { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
