//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Info
    {
        public Login_Info()
        {
            this.Admin = new HashSet<Admin>();
            this.Mechanic = new HashSet<Mechanic>();
        }
    
        public int ID { get; set; }
        public string UserType { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Admin> Admin { get; set; }
        public virtual ICollection<Mechanic> Mechanic { get; set; }
    }
}
