//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mechanic
    {
        public Mechanic()
        {
            this.Description = new HashSet<Description>();
            this.Order = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public string PhoneNumber { get; set; }
        public string WorkExperience { get; set; }
        public int Login_InfoID { get; set; }
    
        public virtual ICollection<Description> Description { get; set; }
        public virtual Login_Info Login_Info { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
