//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Done
    {
        public int ID { get; set; }
        public int DescriptionID { get; set; }
        public int ServiceID { get; set; }
    
        public virtual Description Description { get; set; }
        public virtual Service Service { get; set; }
    }
}
