//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spare
    {
        public Spare()
        {
            this.Spares_Used = new HashSet<Spares_Used>();
        }
    
        public int ID { get; set; }
        public string Naming { get; set; }
        public int Cost { get; set; }
    
        public virtual ICollection<Spares_Used> Spares_Used { get; set; }
    }
}
