//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STOEntities : DbContext
    {
        public STOEntities()
            : base("name=STOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<Car> Car { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<Client_Cars> Client_Cars { get; set; }
        public DbSet<Description> Description { get; set; }
        public DbSet<Login_Info> Login_Info { get; set; }
        public DbSet<Mechanic> Mechanic { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<Service> Service { get; set; }
        public DbSet<Service_Done> Service_Done { get; set; }
        public DbSet<Spare> Spare { get; set; }
        public DbSet<Spares_Used> Spares_Used { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
